trigger:
- main

variables:
  vmName: 'osmar-vm'
  resourceGroupName: 'Test_Osmar'
  location: 'eastus'
  adminUsername: 'azureadmin'
  adminPassword: '220912Caramelos1.'
  vmSize: 'Standard_D2s_v3'
  systemDiskName: 'Test-Osmar-Disk'
  dataDiskName: 'Test-Osmar-dataDisk'
  lockName: 'vm-delete-lock'
  keyVaultName: 'my-keyvault'  # El nombre de tu Key Vault, si deseas guardar la contraseña allí.

stages:
- stage: Provision_VM
  displayName: "Provision Windows VM"
  jobs:
  - job: CreateVM
    displayName: "Create Windows Virtual Machine"
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: AzureCLI@2
      displayName: "Create Resource Group"
      inputs:
        azureSubscription: 'Arroyo_Challenge-Test_Osmar'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName) --location $(location)

    - task: AzureCLI@2
      displayName: "Create Windows VM with System Disk"
      inputs:
        azureSubscription: 'Arroyo_Challenge-Test_Osmar'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az vm create \
            --resource-group $(resourceGroupName) \
            --name $(vmName) \
            --image Win2022Datacenter \
            --size $(vmSize) \
            --admin-username $(adminUsername) \
            --admin-password $(adminPassword) \
            --os-disk-name $(systemDiskName)

    - task: AzureCLI@2
      displayName: "Rotate Admin Password"
      inputs:
        azureSubscription: 'Arroyo_Challenge-Test_Osmar'
        scriptType: 'powershell'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Generar una nueva contraseña aleatoria
          $password = [System.Web.Security.Membership]::GeneratePassword(16, 4)
          powershell.exe -Command "Write-Host "Nueva contraseña generada: $password""

          # Cambiar la contraseña del administrador en la máquina virtual
          $adminUsername = "$(adminUsername)"
          $vmName = "$(vmName)"
          $resourceGroupName = "$(resourceGroupName)"
          
          # Conectar a la VM y cambiar la contraseña
          $vm = az vm show --resource-group $resourceGroupName --name $vmName --query "id" -o tsv
          if (-not $vm) {
            Write-Error "La máquina virtual no se encuentra."
            exit 1
          }
          
          az vm user update \
            --resource-group $resourceGroupName \
            --vm-name $vmName \
            --username $adminUsername \
            --password $password
          
          Write-Host "Contraseña de administrador actualizada exitosamente."

          # Almacenar la nueva contraseña en Azure Key Vault (opcional)
          az keyvault secret set --vault-name $(keyVaultName) --name "AdminPassword" --value $password
          
    

    - task: AzureCLI@2
      displayName: "Validate Environment Setup"
      inputs:
        azureSubscription: 'Arroyo_Challenge-Test_Osmar'
        scriptType: 'powershell'
        scriptLocation: 'inlineScript'
        inlineScript: | 
          echo "Variables de entorno del sistema:"
          powershell.exe -Command "Get-ChildItem Env: | Sort-Object Name"
        shell: powershell
